version: '3.4'
services:

  post_db:
    image: mongo:3.2
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME}/ui:${UI_VER}
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        delay: 5s
        parallelism: 1
        failure_action: pause
      placement:
        constraints:
          - node.role == worker
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - ${H_PORT_UI}:${C_PORT_UI}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${POST_VER}
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        delay: 10s
        parallelism: 2
        failure_action: rollback
      placement:
        constraints:
          - node.role == worker
    networks:
      - back_net
      - front_net
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"

  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        delay: 10s
        parallelism: 2
        failure_action: rollback
      placement:
        constraints:
          - node.role == worker
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.0 
    deploy: 
      mode: global 
    networks:
      - front_net
      - back_net

volumes:
  post_db: {}

networks:
  back_net: {}
  front_net: {}
